// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Check for environment configuration from dotenv
    final environment = dotenv.env['ENVIRONMENT'] ?? 'dev';

    if (environment == 'production') {
      return _getProductionOptions();
    } else {
      return _getDevOptions();
    }
  }

  static FirebaseOptions _getProductionOptions() {
    if (kIsWeb) {
      return webProduction;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return androidProduction;
      case TargetPlatform.iOS:
        return iosProduction;
      case TargetPlatform.macOS:
        return macosProduction;
      case TargetPlatform.windows:
        return windowsProduction;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions _getDevOptions() {
    if (kIsWeb) {
      return webDev;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return androidDev;
      case TargetPlatform.iOS:
        return iosDev;
      case TargetPlatform.macOS:
        return macosDev;
      case TargetPlatform.windows:
        return windowsDev;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Development Environment (maypole-flutter-dev)
  static FirebaseOptions get webDev => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_DEV_WEB_API_KEY'] ?? '',
    appId: dotenv.env['FIREBASE_DEV_WEB_APP_ID'] ?? '',
    messagingSenderId: dotenv.env['FIREBASE_DEV_MESSAGING_SENDER_ID'] ?? '',
    projectId: dotenv.env['FIREBASE_DEV_PROJECT_ID'] ?? 'maypole-flutter-dev',
    authDomain:
        dotenv.env['FIREBASE_DEV_AUTH_DOMAIN'] ??
        'maypole-flutter-dev.firebaseapp.com',
    storageBucket:
        dotenv.env['FIREBASE_DEV_STORAGE_BUCKET'] ??
        'maypole-flutter-dev.firebasestorage.app',
    measurementId: dotenv.env['FIREBASE_DEV_WEB_MEASUREMENT_ID'] ?? '',
  );

  static FirebaseOptions get androidDev => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_DEV_ANDROID_API_KEY'] ?? '',
    appId: dotenv.env['FIREBASE_DEV_ANDROID_APP_ID'] ?? '',
    messagingSenderId: dotenv.env['FIREBASE_DEV_MESSAGING_SENDER_ID'] ?? '',
    projectId: dotenv.env['FIREBASE_DEV_PROJECT_ID'] ?? 'maypole-flutter-dev',
    storageBucket: dotenv.env['FIREBASE_DEV_STORAGE_BUCKET'] ??
        'maypole-flutter-dev.firebasestorage.app',
  );

  static FirebaseOptions get iosDev => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_DEV_IOS_API_KEY'] ?? '',
    appId: dotenv.env['FIREBASE_DEV_IOS_APP_ID'] ?? '',
    messagingSenderId: dotenv.env['FIREBASE_DEV_MESSAGING_SENDER_ID'] ?? '',
    projectId: dotenv.env['FIREBASE_DEV_PROJECT_ID'] ?? 'maypole-flutter-dev',
    storageBucket:
        dotenv.env['FIREBASE_DEV_STORAGE_BUCKET'] ??
        'maypole-flutter-dev.firebasestorage.app',
    iosBundleId: dotenv.env['IOS_BUNDLE_ID'] ?? 'app.maypole.maypole',
  );

  static FirebaseOptions get macosDev => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_DEV_IOS_API_KEY'] ?? '',
    appId: dotenv.env['FIREBASE_DEV_IOS_APP_ID'] ?? '',
    messagingSenderId: dotenv.env['FIREBASE_DEV_MESSAGING_SENDER_ID'] ?? '',
    projectId: dotenv.env['FIREBASE_DEV_PROJECT_ID'] ?? 'maypole-flutter-dev',
    storageBucket:
        dotenv.env['FIREBASE_DEV_STORAGE_BUCKET'] ??
        'maypole-flutter-dev.firebasestorage.app',
    iosBundleId: dotenv.env['IOS_BUNDLE_ID'] ?? 'app.maypole.maypole',
  );

  static FirebaseOptions get windowsDev => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_DEV_WEB_API_KEY'] ?? '',
    appId: dotenv.env['FIREBASE_DEV_WEB_APP_ID'] ?? '',
    messagingSenderId: dotenv.env['FIREBASE_DEV_MESSAGING_SENDER_ID'] ?? '',
    projectId: dotenv.env['FIREBASE_DEV_PROJECT_ID'] ?? 'maypole-flutter-dev',
    authDomain:
        dotenv.env['FIREBASE_DEV_AUTH_DOMAIN'] ??
        'maypole-flutter-dev.firebaseapp.com',
    storageBucket:
        dotenv.env['FIREBASE_DEV_STORAGE_BUCKET'] ??
        'maypole-flutter-dev.firebasestorage.app',
    measurementId: dotenv.env['FIREBASE_DEV_WEB_MEASUREMENT_ID'] ?? '',
  );

  // Production Environment (maypole-flutter-ce6c3)
  static FirebaseOptions get webProduction => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_PROD_WEB_API_KEY'] ?? '',
    appId: dotenv.env['FIREBASE_PROD_WEB_APP_ID'] ?? '',
    messagingSenderId: dotenv.env['FIREBASE_PROD_MESSAGING_SENDER_ID'] ?? '',
    projectId:
        dotenv.env['FIREBASE_PROD_PROJECT_ID'] ?? 'maypole-flutter-ce6c3',
    authDomain:
        dotenv.env['FIREBASE_PROD_AUTH_DOMAIN'] ??
        'maypole-flutter-ce6c3.firebaseapp.com',
    storageBucket:
        dotenv.env['FIREBASE_PROD_STORAGE_BUCKET'] ??
        'maypole-flutter-ce6c3.firebasestorage.app',
    measurementId: dotenv.env['FIREBASE_PROD_WEB_MEASUREMENT_ID'] ?? '',
  );

  static FirebaseOptions get androidProduction => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_PROD_ANDROID_API_KEY'] ?? '',
    appId: dotenv.env['FIREBASE_PROD_ANDROID_APP_ID'] ?? '',
    messagingSenderId: dotenv.env['FIREBASE_PROD_MESSAGING_SENDER_ID'] ?? '',
    projectId:
        dotenv.env['FIREBASE_PROD_PROJECT_ID'] ?? 'maypole-flutter-ce6c3',
    storageBucket:
        dotenv.env['FIREBASE_PROD_STORAGE_BUCKET'] ??
        'maypole-flutter-ce6c3.firebasestorage.app',
  );

  static FirebaseOptions get iosProduction => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_PROD_IOS_API_KEY'] ?? '',
    appId: dotenv.env['FIREBASE_PROD_IOS_APP_ID'] ?? '',
    messagingSenderId: dotenv.env['FIREBASE_PROD_MESSAGING_SENDER_ID'] ?? '',
    projectId:
        dotenv.env['FIREBASE_PROD_PROJECT_ID'] ?? 'maypole-flutter-ce6c3',
    storageBucket:
        dotenv.env['FIREBASE_PROD_STORAGE_BUCKET'] ??
        'maypole-flutter-ce6c3.firebasestorage.app',
    iosBundleId: dotenv.env['IOS_BUNDLE_ID'] ?? 'app.maypole.maypole',
  );

  static FirebaseOptions get macosProduction => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_PROD_IOS_API_KEY'] ?? '',
    appId: dotenv.env['FIREBASE_PROD_IOS_APP_ID'] ?? '',
    messagingSenderId: dotenv.env['FIREBASE_PROD_MESSAGING_SENDER_ID'] ?? '',
    projectId:
        dotenv.env['FIREBASE_PROD_PROJECT_ID'] ?? 'maypole-flutter-ce6c3',
    storageBucket:
        dotenv.env['FIREBASE_PROD_STORAGE_BUCKET'] ??
        'maypole-flutter-ce6c3.firebasestorage.app',
    iosBundleId: dotenv.env['IOS_BUNDLE_ID'] ?? 'app.maypole.maypole',
  );

  static FirebaseOptions get windowsProduction => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_PROD_WEB_API_KEY'] ?? '',
    appId: dotenv.env['FIREBASE_PROD_WINDOWS_APP_ID'] ?? '',
    messagingSenderId: dotenv.env['FIREBASE_PROD_MESSAGING_SENDER_ID'] ?? '',
    projectId:
        dotenv.env['FIREBASE_PROD_PROJECT_ID'] ?? 'maypole-flutter-ce6c3',
    authDomain:
        dotenv.env['FIREBASE_PROD_AUTH_DOMAIN'] ??
        'maypole-flutter-ce6c3.firebaseapp.com',
    storageBucket:
        dotenv.env['FIREBASE_PROD_STORAGE_BUCKET'] ??
        'maypole-flutter-ce6c3.firebasestorage.app',
    measurementId: dotenv.env['FIREBASE_PROD_WINDOWS_MEASUREMENT_ID'] ?? '',
  );
}