// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6CdLLhnvhcRCMQDcPs6OxvRKnLC1ey1Y',
    appId: '1:1069925301177:web:b34f1952febe6bce4e1468',
    messagingSenderId: '1069925301177',
    projectId: 'maypole-flutter-ce6c3',
    authDomain: 'maypole-flutter-ce6c3.firebaseapp.com',
    storageBucket: 'maypole-flutter-ce6c3.firebasestorage.app',
    measurementId: 'G-YTP58985GW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAySMsqTui6rG0iVCc4f3fmMhwLfsMd-W0',
    appId: '1:1069925301177:android:6c087b01bcd4f66c4e1468',
    messagingSenderId: '1069925301177',
    projectId: 'maypole-flutter-ce6c3',
    storageBucket: 'maypole-flutter-ce6c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFvVqMZ3hvmsCbvLm1tXPyWnD5KcmMNhU',
    appId: '1:1069925301177:ios:c53b497e66d5e9c24e1468',
    messagingSenderId: '1069925301177',
    projectId: 'maypole-flutter-ce6c3',
    storageBucket: 'maypole-flutter-ce6c3.firebasestorage.app',
    iosBundleId: 'app.maypole.maypole',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFvVqMZ3hvmsCbvLm1tXPyWnD5KcmMNhU',
    appId: '1:1069925301177:ios:c53b497e66d5e9c24e1468',
    messagingSenderId: '1069925301177',
    projectId: 'maypole-flutter-ce6c3',
    storageBucket: 'maypole-flutter-ce6c3.firebasestorage.app',
    iosBundleId: 'app.maypole.maypole',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6CdLLhnvhcRCMQDcPs6OxvRKnLC1ey1Y',
    appId: '1:1069925301177:web:a55c1912085f464e4e1468',
    messagingSenderId: '1069925301177',
    projectId: 'maypole-flutter-ce6c3',
    authDomain: 'maypole-flutter-ce6c3.firebaseapp.com',
    storageBucket: 'maypole-flutter-ce6c3.firebasestorage.app',
    measurementId: 'G-NZ5CEHM1T9',
  );

}