// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Check for environment configuration
    const environment = String.fromEnvironment(
        'ENVIRONMENT', defaultValue: 'dev');

    if (environment == 'production') {
      return _getProductionOptions();
    } else {
      return _getDevOptions();
    }
  }

  static FirebaseOptions _getProductionOptions() {
    if (kIsWeb) {
      return webProduction;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return androidProduction;
      case TargetPlatform.iOS:
        return iosProduction;
      case TargetPlatform.macOS:
        return macosProduction;
      case TargetPlatform.windows:
        return windowsProduction;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions _getDevOptions() {
    if (kIsWeb) {
      return webDev;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return androidDev;
      case TargetPlatform.iOS:
        return iosDev;
      case TargetPlatform.macOS:
        return macosDev;
      case TargetPlatform.windows:
        return windowsDev;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Development Environment (maypole-flutter-dev)
  static const FirebaseOptions webDev = FirebaseOptions(
    apiKey: String.fromEnvironment(
        'FIREBASE_DEV_WEB_API_KEY', defaultValue: ''),
    appId: String.fromEnvironment('FIREBASE_DEV_WEB_APP_ID', defaultValue: ''),
    messagingSenderId: String.fromEnvironment(
        'FIREBASE_DEV_MESSAGING_SENDER_ID', defaultValue: ''),
    projectId: String.fromEnvironment(
        'FIREBASE_DEV_PROJECT_ID', defaultValue: 'maypole-flutter-dev'),
    authDomain: String.fromEnvironment('FIREBASE_DEV_AUTH_DOMAIN',
        defaultValue: 'maypole-flutter-dev.firebaseapp.com'),
    storageBucket: String.fromEnvironment('FIREBASE_DEV_STORAGE_BUCKET',
        defaultValue: 'maypole-flutter-dev.firebasestorage.app'),
    measurementId: String.fromEnvironment(
        'FIREBASE_DEV_WEB_MEASUREMENT_ID', defaultValue: ''),
  );

  static const FirebaseOptions androidDev = FirebaseOptions(
    apiKey: String.fromEnvironment(
        'FIREBASE_DEV_ANDROID_API_KEY', defaultValue: ''),
    appId: String.fromEnvironment(
        'FIREBASE_DEV_ANDROID_APP_ID', defaultValue: ''),
    messagingSenderId: String.fromEnvironment(
        'FIREBASE_DEV_MESSAGING_SENDER_ID', defaultValue: ''),
    projectId: String.fromEnvironment(
        'FIREBASE_DEV_PROJECT_ID', defaultValue: 'maypole-flutter-dev'),
    storageBucket: String.fromEnvironment('FIREBASE_DEV_STORAGE_BUCKET',
        defaultValue: 'maypole-flutter-dev.firebasestorage.app'),
  );

  static const FirebaseOptions iosDev = FirebaseOptions(
    apiKey: String.fromEnvironment(
        'FIREBASE_DEV_IOS_API_KEY', defaultValue: ''),
    appId: String.fromEnvironment('FIREBASE_DEV_IOS_APP_ID', defaultValue: ''),
    messagingSenderId: String.fromEnvironment(
        'FIREBASE_DEV_MESSAGING_SENDER_ID', defaultValue: ''),
    projectId: String.fromEnvironment(
        'FIREBASE_DEV_PROJECT_ID', defaultValue: 'maypole-flutter-dev'),
    storageBucket: String.fromEnvironment('FIREBASE_DEV_STORAGE_BUCKET',
        defaultValue: 'maypole-flutter-dev.firebasestorage.app'),
    iosBundleId: String.fromEnvironment(
        'IOS_BUNDLE_ID', defaultValue: 'app.maypole.maypole'),
  );

  static const FirebaseOptions macosDev = FirebaseOptions(
    apiKey: String.fromEnvironment(
        'FIREBASE_DEV_IOS_API_KEY', defaultValue: ''),
    appId: String.fromEnvironment('FIREBASE_DEV_IOS_APP_ID', defaultValue: ''),
    messagingSenderId: String.fromEnvironment(
        'FIREBASE_DEV_MESSAGING_SENDER_ID', defaultValue: ''),
    projectId: String.fromEnvironment(
        'FIREBASE_DEV_PROJECT_ID', defaultValue: 'maypole-flutter-dev'),
    storageBucket: String.fromEnvironment('FIREBASE_DEV_STORAGE_BUCKET',
        defaultValue: 'maypole-flutter-dev.firebasestorage.app'),
    iosBundleId: String.fromEnvironment(
        'IOS_BUNDLE_ID', defaultValue: 'app.maypole.maypole'),
  );

  static const FirebaseOptions windowsDev = FirebaseOptions(
    apiKey: String.fromEnvironment(
        'FIREBASE_DEV_WEB_API_KEY', defaultValue: ''),
    appId: String.fromEnvironment('FIREBASE_DEV_WEB_APP_ID', defaultValue: ''),
    messagingSenderId: String.fromEnvironment(
        'FIREBASE_DEV_MESSAGING_SENDER_ID', defaultValue: ''),
    projectId: String.fromEnvironment(
        'FIREBASE_DEV_PROJECT_ID', defaultValue: 'maypole-flutter-dev'),
    authDomain: String.fromEnvironment('FIREBASE_DEV_AUTH_DOMAIN',
        defaultValue: 'maypole-flutter-dev.firebaseapp.com'),
    storageBucket: String.fromEnvironment('FIREBASE_DEV_STORAGE_BUCKET',
        defaultValue: 'maypole-flutter-dev.firebasestorage.app'),
    measurementId: String.fromEnvironment(
        'FIREBASE_DEV_WEB_MEASUREMENT_ID', defaultValue: ''),
  );

  // Production Environment (maypole-flutter-ce6c3)
  static const FirebaseOptions webProduction = FirebaseOptions(
    apiKey: String.fromEnvironment(
        'FIREBASE_PROD_WEB_API_KEY', defaultValue: ''),
    appId: String.fromEnvironment('FIREBASE_PROD_WEB_APP_ID', defaultValue: ''),
    messagingSenderId: String.fromEnvironment(
        'FIREBASE_PROD_MESSAGING_SENDER_ID', defaultValue: ''),
    projectId: String.fromEnvironment(
        'FIREBASE_PROD_PROJECT_ID', defaultValue: 'maypole-flutter-ce6c3'),
    authDomain: String.fromEnvironment('FIREBASE_PROD_AUTH_DOMAIN',
        defaultValue: 'maypole-flutter-ce6c3.firebaseapp.com'),
    storageBucket: String.fromEnvironment('FIREBASE_PROD_STORAGE_BUCKET',
        defaultValue: 'maypole-flutter-ce6c3.firebasestorage.app'),
    measurementId: String.fromEnvironment(
        'FIREBASE_PROD_WEB_MEASUREMENT_ID', defaultValue: ''),
  );

  static const FirebaseOptions androidProduction = FirebaseOptions(
    apiKey: String.fromEnvironment(
        'FIREBASE_PROD_ANDROID_API_KEY', defaultValue: ''),
    appId: String.fromEnvironment(
        'FIREBASE_PROD_ANDROID_APP_ID', defaultValue: ''),
    messagingSenderId: String.fromEnvironment(
        'FIREBASE_PROD_MESSAGING_SENDER_ID', defaultValue: ''),
    projectId: String.fromEnvironment(
        'FIREBASE_PROD_PROJECT_ID', defaultValue: 'maypole-flutter-ce6c3'),
    storageBucket: String.fromEnvironment('FIREBASE_PROD_STORAGE_BUCKET',
        defaultValue: 'maypole-flutter-ce6c3.firebasestorage.app'),
  );

  static const FirebaseOptions iosProduction = FirebaseOptions(
    apiKey: String.fromEnvironment(
        'FIREBASE_PROD_IOS_API_KEY', defaultValue: ''),
    appId: String.fromEnvironment('FIREBASE_PROD_IOS_APP_ID', defaultValue: ''),
    messagingSenderId: String.fromEnvironment(
        'FIREBASE_PROD_MESSAGING_SENDER_ID', defaultValue: ''),
    projectId: String.fromEnvironment(
        'FIREBASE_PROD_PROJECT_ID', defaultValue: 'maypole-flutter-ce6c3'),
    storageBucket: String.fromEnvironment('FIREBASE_PROD_STORAGE_BUCKET',
        defaultValue: 'maypole-flutter-ce6c3.firebasestorage.app'),
    iosBundleId: String.fromEnvironment(
        'IOS_BUNDLE_ID', defaultValue: 'app.maypole.maypole'),
  );

  static const FirebaseOptions macosProduction = FirebaseOptions(
    apiKey: String.fromEnvironment(
        'FIREBASE_PROD_IOS_API_KEY', defaultValue: ''),
    appId: String.fromEnvironment('FIREBASE_PROD_IOS_APP_ID', defaultValue: ''),
    messagingSenderId: String.fromEnvironment(
        'FIREBASE_PROD_MESSAGING_SENDER_ID', defaultValue: ''),
    projectId: String.fromEnvironment(
        'FIREBASE_PROD_PROJECT_ID', defaultValue: 'maypole-flutter-ce6c3'),
    storageBucket: String.fromEnvironment('FIREBASE_PROD_STORAGE_BUCKET',
        defaultValue: 'maypole-flutter-ce6c3.firebasestorage.app'),
    iosBundleId: String.fromEnvironment(
        'IOS_BUNDLE_ID', defaultValue: 'app.maypole.maypole'),
  );

  static const FirebaseOptions windowsProduction = FirebaseOptions(
    apiKey: String.fromEnvironment(
        'FIREBASE_PROD_WEB_API_KEY', defaultValue: ''),
    appId: String.fromEnvironment(
        'FIREBASE_PROD_WINDOWS_APP_ID', defaultValue: ''),
    messagingSenderId: String.fromEnvironment(
        'FIREBASE_PROD_MESSAGING_SENDER_ID', defaultValue: ''),
    projectId: String.fromEnvironment(
        'FIREBASE_PROD_PROJECT_ID', defaultValue: 'maypole-flutter-ce6c3'),
    authDomain: String.fromEnvironment('FIREBASE_PROD_AUTH_DOMAIN',
        defaultValue: 'maypole-flutter-ce6c3.firebaseapp.com'),
    storageBucket: String.fromEnvironment('FIREBASE_PROD_STORAGE_BUCKET',
        defaultValue: 'maypole-flutter-ce6c3.firebasestorage.app'),
    measurementId: String.fromEnvironment(
        'FIREBASE_PROD_WINDOWS_MEASUREMENT_ID', defaultValue: ''),
  );

}