// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // Helper methods to get specific environment variables with dart-define priority
  static String _getEnvironment() {
    const String dartDefineValue = String.fromEnvironment(
        'ENVIRONMENT', defaultValue: '');
    if (dartDefineValue.isNotEmpty) return dartDefineValue;
    try {
      return dotenv.env['ENVIRONMENT'] ?? 'dev';
    } catch (e) {
      return 'dev';
    }
  }

  static String _getFirebaseDevWebApiKey() {
    const String dartDefineValue = String.fromEnvironment(
        'FIREBASE_DEV_WEB_API_KEY', defaultValue: '');
    if (dartDefineValue.isNotEmpty) return dartDefineValue;
    try {
      return dotenv.env['FIREBASE_DEV_WEB_API_KEY'] ?? '';
    } catch (e) {
      return '';
    }
  }

  static String _getFirebaseDevWebAppId() {
    const String dartDefineValue = String.fromEnvironment(
        'FIREBASE_DEV_WEB_APP_ID', defaultValue: '');
    if (dartDefineValue.isNotEmpty) return dartDefineValue;
    try {
      return dotenv.env['FIREBASE_DEV_WEB_APP_ID'] ?? '';
    } catch (e) {
      return '';
    }
  }

  static String _getFirebaseDevMessagingSenderId() {
    const String dartDefineValue = String.fromEnvironment(
        'FIREBASE_DEV_MESSAGING_SENDER_ID', defaultValue: '');
    if (dartDefineValue.isNotEmpty) return dartDefineValue;
    try {
      return dotenv.env['FIREBASE_DEV_MESSAGING_SENDER_ID'] ?? '';
    } catch (e) {
      return '';
    }
  }

  static String _getFirebaseDevProjectId() {
    const String dartDefineValue = String.fromEnvironment(
        'FIREBASE_DEV_PROJECT_ID', defaultValue: '');
    if (dartDefineValue.isNotEmpty) return dartDefineValue;
    try {
      return dotenv.env['FIREBASE_DEV_PROJECT_ID'] ?? '';
    } catch (e) {
      return '';
    }
  }

  static String _getFirebaseDevAuthDomain() {
    const String dartDefineValue = String.fromEnvironment(
        'FIREBASE_DEV_AUTH_DOMAIN', defaultValue: '');
    if (dartDefineValue.isNotEmpty) return dartDefineValue;
    try {
      return dotenv.env['FIREBASE_DEV_AUTH_DOMAIN'] ?? '';
    } catch (e) {
      return '';
    }
  }

  static String _getFirebaseDevStorageBucket() {
    const String dartDefineValue = String.fromEnvironment(
        'FIREBASE_DEV_STORAGE_BUCKET', defaultValue: '');
    if (dartDefineValue.isNotEmpty) return dartDefineValue;
    try {
      return dotenv.env['FIREBASE_DEV_STORAGE_BUCKET'] ?? '';
    } catch (e) {
      return '';
    }
  }

  static String _getFirebaseDevWebMeasurementId() {
    const String dartDefineValue = String.fromEnvironment(
        'FIREBASE_DEV_WEB_MEASUREMENT_ID', defaultValue: '');
    if (dartDefineValue.isNotEmpty) return dartDefineValue;
    try {
      return dotenv.env['FIREBASE_DEV_WEB_MEASUREMENT_ID'] ?? '';
    } catch (e) {
      return '';
    }
  }

  static String _getFirebaseDevAndroidApiKey() {
    const String dartDefineValue = String.fromEnvironment(
        'FIREBASE_DEV_ANDROID_API_KEY', defaultValue: '');
    if (dartDefineValue.isNotEmpty) return dartDefineValue;
    try {
      return dotenv.env['FIREBASE_DEV_ANDROID_API_KEY'] ?? '';
    } catch (e) {
      return '';
    }
  }

  static String _getFirebaseDevAndroidAppId() {
    const String dartDefineValue = String.fromEnvironment(
        'FIREBASE_DEV_ANDROID_APP_ID', defaultValue: '');
    if (dartDefineValue.isNotEmpty) return dartDefineValue;
    try {
      return dotenv.env['FIREBASE_DEV_ANDROID_APP_ID'] ?? '';
    } catch (e) {
      return '';
    }
  }

  static String _getFirebaseDevIosApiKey() {
    const String dartDefineValue = String.fromEnvironment(
        'FIREBASE_DEV_IOS_API_KEY', defaultValue: '');
    if (dartDefineValue.isNotEmpty) return dartDefineValue;
    try {
      return dotenv.env['FIREBASE_DEV_IOS_API_KEY'] ?? '';
    } catch (e) {
      return '';
    }
  }

  static String _getFirebaseDevIosAppId() {
    const String dartDefineValue = String.fromEnvironment(
        'FIREBASE_DEV_IOS_APP_ID', defaultValue: '');
    if (dartDefineValue.isNotEmpty) return dartDefineValue;
    try {
      return dotenv.env['FIREBASE_DEV_IOS_APP_ID'] ?? '';
    } catch (e) {
      return '';
    }
  }

  static String _getIosBundleId() {
    const String dartDefineValue = String.fromEnvironment(
        'IOS_BUNDLE_ID', defaultValue: '');
    if (dartDefineValue.isNotEmpty) return dartDefineValue;
    try {
      return dotenv.env['IOS_BUNDLE_ID'] ?? '';
    } catch (e) {
      return '';
    }
  }

  // Production environment getters
  static String _getFirebaseProdWebApiKey() {
    const String dartDefineValue = String.fromEnvironment(
        'FIREBASE_PROD_WEB_API_KEY', defaultValue: '');
    if (dartDefineValue.isNotEmpty) return dartDefineValue;
    try {
      return dotenv.env['FIREBASE_PROD_WEB_API_KEY'] ?? '';
    } catch (e) {
      return '';
    }
  }

  static String _getFirebaseProdWebAppId() {
    const String dartDefineValue = String.fromEnvironment(
        'FIREBASE_PROD_WEB_APP_ID', defaultValue: '');
    if (dartDefineValue.isNotEmpty) return dartDefineValue;
    try {
      return dotenv.env['FIREBASE_PROD_WEB_APP_ID'] ?? '';
    } catch (e) {
      return '';
    }
  }

  static String _getFirebaseProdMessagingSenderId() {
    const String dartDefineValue = String.fromEnvironment(
        'FIREBASE_PROD_MESSAGING_SENDER_ID', defaultValue: '');
    if (dartDefineValue.isNotEmpty) return dartDefineValue;
    try {
      return dotenv.env['FIREBASE_PROD_MESSAGING_SENDER_ID'] ?? '';
    } catch (e) {
      return '';
    }
  }

  static String _getFirebaseProdProjectId() {
    const String dartDefineValue = String.fromEnvironment(
        'FIREBASE_PROD_PROJECT_ID', defaultValue: '');
    if (dartDefineValue.isNotEmpty) return dartDefineValue;
    try {
      return dotenv.env['FIREBASE_PROD_PROJECT_ID'] ?? '';
    } catch (e) {
      return '';
    }
  }

  static String _getFirebaseProdAuthDomain() {
    const String dartDefineValue = String.fromEnvironment(
        'FIREBASE_PROD_AUTH_DOMAIN', defaultValue: '');
    if (dartDefineValue.isNotEmpty) return dartDefineValue;
    try {
      return dotenv.env['FIREBASE_PROD_AUTH_DOMAIN'] ?? '';
    } catch (e) {
      return '';
    }
  }

  static String _getFirebaseProdStorageBucket() {
    const String dartDefineValue = String.fromEnvironment(
        'FIREBASE_PROD_STORAGE_BUCKET', defaultValue: '');
    if (dartDefineValue.isNotEmpty) return dartDefineValue;
    try {
      return dotenv.env['FIREBASE_PROD_STORAGE_BUCKET'] ?? '';
    } catch (e) {
      return '';
    }
  }

  static String _getFirebaseProdWebMeasurementId() {
    const String dartDefineValue = String.fromEnvironment(
        'FIREBASE_PROD_WEB_MEASUREMENT_ID', defaultValue: '');
    if (dartDefineValue.isNotEmpty) return dartDefineValue;
    try {
      return dotenv.env['FIREBASE_PROD_WEB_MEASUREMENT_ID'] ?? '';
    } catch (e) {
      return '';
    }
  }

  static String _getFirebaseProdAndroidApiKey() {
    const String dartDefineValue = String.fromEnvironment(
        'FIREBASE_PROD_ANDROID_API_KEY', defaultValue: '');
    if (dartDefineValue.isNotEmpty) return dartDefineValue;
    try {
      return dotenv.env['FIREBASE_PROD_ANDROID_API_KEY'] ?? '';
    } catch (e) {
      return '';
    }
  }

  static String _getFirebaseProdAndroidAppId() {
    const String dartDefineValue = String.fromEnvironment(
        'FIREBASE_PROD_ANDROID_APP_ID', defaultValue: '');
    if (dartDefineValue.isNotEmpty) return dartDefineValue;
    try {
      return dotenv.env['FIREBASE_PROD_ANDROID_APP_ID'] ?? '';
    } catch (e) {
      return '';
    }
  }

  static String _getFirebaseProdIosApiKey() {
    const String dartDefineValue = String.fromEnvironment(
        'FIREBASE_PROD_IOS_API_KEY', defaultValue: '');
    if (dartDefineValue.isNotEmpty) return dartDefineValue;
    try {
      return dotenv.env['FIREBASE_PROD_IOS_API_KEY'] ?? '';
    } catch (e) {
      return '';
    }
  }

  static String _getFirebaseProdIosAppId() {
    const String dartDefineValue = String.fromEnvironment(
        'FIREBASE_PROD_IOS_APP_ID', defaultValue: '');
    if (dartDefineValue.isNotEmpty) return dartDefineValue;
    try {
      return dotenv.env['FIREBASE_PROD_IOS_APP_ID'] ?? '';
    } catch (e) {
      return '';
    }
  }

  static String _getFirebaseProdWindowsAppId() {
    const String dartDefineValue = String.fromEnvironment(
        'FIREBASE_PROD_WINDOWS_APP_ID', defaultValue: '');
    if (dartDefineValue.isNotEmpty) return dartDefineValue;
    try {
      return dotenv.env['FIREBASE_PROD_WINDOWS_APP_ID'] ?? '';
    } catch (e) {
      return '';
    }
  }

  static String _getFirebaseProdWindowsMeasurementId() {
    const String dartDefineValue = String.fromEnvironment(
        'FIREBASE_PROD_WINDOWS_MEASUREMENT_ID', defaultValue: '');
    if (dartDefineValue.isNotEmpty) return dartDefineValue;
    try {
      return dotenv.env['FIREBASE_PROD_WINDOWS_MEASUREMENT_ID'] ?? '';
    } catch (e) {
      return '';
    }
  }

  static FirebaseOptions get currentPlatform {
    // Get environment from dart-define, fallback to dotenv, then default to dev
    final environment = _getEnvironment();

    if (kIsWeb) {
      // Debug logging for web to help diagnose configuration issues
      print('🔧 Firebase Config Debug:');
      print('  Environment: $environment');
      print('  Platform: Web');
    }

    if (environment == 'production' || environment == 'prod') {
      return _getProductionOptions();
    } else {
      return _getDevOptions();
    }
  }

  static FirebaseOptions _getProductionOptions() {
    if (kIsWeb) {
      return webProduction;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return androidProduction;
      case TargetPlatform.iOS:
        return iosProduction;
      case TargetPlatform.macOS:
        return macosProduction;
      case TargetPlatform.windows:
        return windowsProduction;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions _getDevOptions() {
    if (kIsWeb) {
      return webDev;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return androidDev;
      case TargetPlatform.iOS:
        return iosDev;
      case TargetPlatform.macOS:
        return macosDev;
      case TargetPlatform.windows:
        return windowsDev;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Development Environment (maypole-flutter-dev)
  static FirebaseOptions get webDev {
    final apiKey = _getFirebaseDevWebApiKey();
    final appId = _getFirebaseDevWebAppId();
    final messagingSenderId = _getFirebaseDevMessagingSenderId();
    final projectId = _getFirebaseDevProjectId();
    final authDomain = _getFirebaseDevAuthDomain();
    final storageBucket = _getFirebaseDevStorageBucket();
    final measurementId = _getFirebaseDevWebMeasurementId();

    if (kIsWeb) {
      print('  API Key: ${apiKey.isEmpty ? "❌ MISSING" : "✅ Present (${apiKey
          .substring(0, 10)}...)"}');
      print('  App ID: ${appId.isEmpty ? "❌ MISSING" : "✅ Present"}');
      print('  Project ID: ${projectId.isEmpty ? "❌ MISSING" : projectId}');
      print('  Auth Domain: ${authDomain.isEmpty ? "❌ MISSING" : authDomain}');
    }

    return FirebaseOptions(
      apiKey: apiKey,
      appId: appId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      authDomain: authDomain,
      storageBucket: storageBucket,
      measurementId: measurementId,
    );
  }

  static FirebaseOptions get androidDev => FirebaseOptions(
    apiKey: _getFirebaseDevAndroidApiKey(),
    appId: _getFirebaseDevAndroidAppId(),
    messagingSenderId: _getFirebaseDevMessagingSenderId(),
    projectId: _getFirebaseDevProjectId(),
    storageBucket: _getFirebaseDevStorageBucket(),
  );

  static FirebaseOptions get iosDev => FirebaseOptions(
    apiKey: _getFirebaseDevIosApiKey(),
    appId: _getFirebaseDevIosAppId(),
    messagingSenderId: _getFirebaseDevMessagingSenderId(),
    projectId: _getFirebaseDevProjectId(),
    storageBucket: _getFirebaseDevStorageBucket(),
    iosBundleId: _getIosBundleId(),
  );

  static FirebaseOptions get macosDev => FirebaseOptions(
    apiKey: _getFirebaseDevIosApiKey(),
    appId: _getFirebaseDevIosAppId(),
    messagingSenderId: _getFirebaseDevMessagingSenderId(),
    projectId: _getFirebaseDevProjectId(),
    storageBucket: _getFirebaseDevStorageBucket(),
    iosBundleId: _getIosBundleId(),
  );

  static FirebaseOptions get windowsDev => FirebaseOptions(
    apiKey: _getFirebaseDevWebApiKey(),
    appId: _getFirebaseDevWebAppId(),
    messagingSenderId: _getFirebaseDevMessagingSenderId(),
    projectId: _getFirebaseDevProjectId(),
    authDomain: _getFirebaseDevAuthDomain(),
    storageBucket: _getFirebaseDevStorageBucket(),
    measurementId: _getFirebaseDevWebMeasurementId(),
  );

  // Production Environment (maypole-flutter-ce6c3)
  static FirebaseOptions get webProduction {
    final apiKey = _getFirebaseProdWebApiKey();
    final appId = _getFirebaseProdWebAppId();
    final messagingSenderId = _getFirebaseProdMessagingSenderId();
    final projectId = _getFirebaseProdProjectId();
    final authDomain = _getFirebaseProdAuthDomain();
    final storageBucket = _getFirebaseProdStorageBucket();
    final measurementId = _getFirebaseProdWebMeasurementId();

    if (kIsWeb) {
      print('  API Key: ${apiKey.isEmpty ? "❌ MISSING" : "✅ Present (${apiKey
          .substring(0, 10)}...)"}');
      print('  App ID: ${appId.isEmpty ? "❌ MISSING" : "✅ Present"}');
      print('  Project ID: ${projectId.isEmpty ? "❌ MISSING" : projectId}');
      print('  Auth Domain: ${authDomain.isEmpty ? "❌ MISSING" : authDomain}');
    }

    return FirebaseOptions(
      apiKey: apiKey,
      appId: appId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      authDomain: authDomain,
      storageBucket: storageBucket,
      measurementId: measurementId,
    );
  }

  static FirebaseOptions get androidProduction => FirebaseOptions(
    apiKey: _getFirebaseProdAndroidApiKey(),
    appId: _getFirebaseProdAndroidAppId(),
    messagingSenderId: _getFirebaseProdMessagingSenderId(),
    projectId: _getFirebaseProdProjectId(),
    storageBucket: _getFirebaseProdStorageBucket(),
  );

  static FirebaseOptions get iosProduction => FirebaseOptions(
    apiKey: _getFirebaseProdIosApiKey(),
    appId: _getFirebaseProdIosAppId(),
    messagingSenderId: _getFirebaseProdMessagingSenderId(),
    projectId: _getFirebaseProdProjectId(),
    storageBucket: _getFirebaseProdStorageBucket(),
    iosBundleId: _getIosBundleId(),
  );

  static FirebaseOptions get macosProduction => FirebaseOptions(
    apiKey: _getFirebaseProdIosApiKey(),
    appId: _getFirebaseProdIosAppId(),
    messagingSenderId: _getFirebaseProdMessagingSenderId(),
    projectId: _getFirebaseProdProjectId(),
    storageBucket: _getFirebaseProdStorageBucket(),
    iosBundleId: _getIosBundleId(),
  );

  static FirebaseOptions get windowsProduction => FirebaseOptions(
    apiKey: _getFirebaseProdWebApiKey(),
    appId: _getFirebaseProdWindowsAppId(),
    messagingSenderId: _getFirebaseProdMessagingSenderId(),
    projectId: _getFirebaseProdProjectId(),
    authDomain: _getFirebaseProdAuthDomain(),
    storageBucket: _getFirebaseProdStorageBucket(),
    measurementId: _getFirebaseProdWindowsMeasurementId(),
  );
}